export const Symbols = {
  GOLDDRAGON: 0,
  GREENDRAGON: 1,
  FISH: 2,
  TURTLE: 3,
  FAN: 4,
  LOTUSFLOWER: 5,
  ACE: 6,
  KING: 7,
  QUEEN: 8,
  JACK: 9,
  TEN: 10,
  NINE: 11,
  YINYANG: 12,
  INNER: 13,
} as const

export const SYM_NAMES = [
  'GOLDDRAGON',
  'GREENDRAGON',
  'FISH',
  'TURTLE',
  'FAN',
  'LOTUSFLOWER',
  'ACE',
  'KING',
  'QUEEN',
  'JACK',
  'TEN',
  'NINE',
  'YINYANG',
  'INNER',
] as const

export const PAY_TABLE: readonly (readonly number[])[] = [
  [0, 5, 50, 1000], // GOLDDRAGON
  [0, 20, 100, 300], // GREENDRAGON
  [0, 20, 50, 200], // FISH
  [0, 20, 50, 200], // TURTLE
  [0, 15, 50, 150], // FAN
  [0, 10, 50, 150], // LOTUSFLOWER
  [0, 5, 50, 100], // ACE
  [0, 5, 50, 100], // KING
  [0, 5, 25, 100], // QUEEN
  [0, 5, 25, 100], // JACK
  [0, 5, 25, 100], // TEN
  [0, 5, 25, 100], // NINE
  [0, 0, 0, 0], // YINYANG scatter
] as const

export const SCATTER_PAY = [0, 0, 1, 5, 10, 500] as const
import { BetConfiguration } from '@tgslots/slots-core/betting/config'
export const BET_CONFIG = BetConfiguration.fromBaseCostAndLineCount(30, 100)

export const PAYLINE_DATA = new Uint8Array([
  1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 0, 2, 2, 1,
  2, 2, 1, 0, 1, 0, 1, 1, 2, 1, 2, 1, 0, 1, 0, 1, 0, 2, 1, 2, 1, 2, 1, 0, 0, 0, 1, 1, 2, 2, 2, 1, 0,
  1, 1, 1, 0, 2, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 0, 2, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 2,
  0, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 1, 1, 2, 0, 2, 1,
])

export const STRIP_STRINGS: readonly string[][] = [
  [
    'JACK',
    'GREENDRAGON',
    'QUEEN',
    'KING',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'GREENDRAGON',
    'QUEEN',
    'ACE',
    'YINYANG',
    'KING',
    'QUEEN',
    'JACK',
    'GOLDDRAGON',
    'QUEEN',
    'ACE',
    'TURTLE',
    'JACK',
    'QUEEN',
    'FISH',
    'JACK',
    'QUEEN',
    'FISH',
    'TEN',
    'KING',
    'NINE',
    'GREENDRAGON',
    'KING',
    'TURTLE',
    'TEN',
    'JACK',
    'GOLDDRAGON',
    'KING',
    'TEN',
    'YINYANG',
    'KING',
    'ACE',
    'GOLDDRAGON',
    'NINE',
  ],
  [
    'TEN',
    'ACE',
    'TURTLE',
    'QUEEN',
    'TEN',
    'GOLDDRAGON',
    'QUEEN',
    'JACK',
    'GREENDRAGON',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'KING',
    'JACK',
    'GOLDDRAGON',
    'ACE',
    'TURTLE',
    'NINE',
    'ACE',
    'YINYANG',
    'QUEEN',
    'JACK',
    'TURTLE',
    'ACE',
    'JACK',
    'LOTUSFLOWER',
    'ACE',
    'GREENDRAGON',
    'TEN',
    'GOLDDRAGON',
    'KING',
    'FISH',
    'ACE',
    'NINE',
    'YINYANG',
    'FISH',
    'KING',
    'GOLDDRAGON',
  ],
  [
    'LOTUSFLOWER',
    'QUEEN',
    'FISH',
    'KING',
    'YINYANG',
    'TEN',
    'FISH',
    'QUEEN',
    'KING',
    'TURTLE',
    'ACE',
    'TEN',
    'GREENDRAGON',
    'NINE',
    'FISH',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'GREENDRAGON',
    'JACK',
    'GOLDDRAGON',
    'QUEEN',
    'FISH',
    'TEN',
    'GREENDRAGON',
    'ACE',
    'TURTLE',
    'QUEEN',
    'GREENDRAGON',
    'ACE',
    'TURTLE',
    'QUEEN',
    'FISH',
    'TEN',
    'GREENDRAGON',
    'ACE',
    'FISH',
    'TEN',
    'GREENDRAGON',
    'ACE',
    'GOLDDRAGON',
    'KING',
    'TURTLE',
    'ACE',
  ],
  [
    'KING',
    'GREENDRAGON',
    'QUEEN',
    'TURTLE',
    'TEN',
    'FISH',
    'NINE',
    'TURTLE',
    'JACK',
    'FISH',
    'QUEEN',
    'TEN',
    'YINYANG',
    'JACK',
    'GOLDDRAGON',
    'KING',
    'NINE',
    'TURTLE',
    'FISH',
    'TEN',
    'GOLDDRAGON',
    'NINE',
    'GREENDRAGON',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'GOLDDRAGON',
    'KING',
    'FISH',
    'NINE',
    'TURTLE',
    'JACK',
    'LOTUSFLOWER',
    'NINE',
    'FISH',
    'ACE',
    'GOLDDRAGON',
  ],
  [
    'JACK',
    'ACE',
    'FISH',
    'TEN',
    'ACE',
    'FISH',
    'JACK',
    'GOLDDRAGON',
    'QUEEN',
    'ACE',
    'GREENDRAGON',
    'JACK',
    'KING',
    'LOTUSFLOWER',
    'KING',
    'KING',
    'TURTLE',
    'TEN',
    'GREENDRAGON',
    'FISH',
    'JACK',
    'FISH',
    'GREENDRAGON',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'FAN',
    'GREENDRAGON',
    'KING',
    'GOLDDRAGON',
    'TEN',
    'NINE',
    'YINYANG',
    'TURTLE',
    'TEN',
    'NINE',
    'ACE',
    'TURTLE',
  ],
]

export const INNER_WEIGHTS: readonly (readonly [number, number])[] = [
  [Symbols.GREENDRAGON, 2],
  [Symbols.FISH, 4],
  [Symbols.TURTLE, 4],
  [Symbols.FAN, 4],
  [Symbols.ACE, 5],
  [Symbols.KING, 5],
  [Symbols.QUEEN, 5],
  [Symbols.JACK, 6],
  [Symbols.TEN, 5],
  [Symbols.NINE, 5],
]
