export const ANIMATION_CONFIG = {
  LOCK_ON_DELAY_MS: 120,
  INTER_MISSILE_PAUSE_MS: 70,
  MISSILE_FLIGHT_MS: 480,
  POST_COMBAT_SETTLE_MS: 120,
  BADGE_DRIFT_DELAY_S: 0.2,
  BADGE_DRIFT_DURATION_S: 0.3,
  TRAIL_LEN: 22,
  SYMBOL_DESIGN_SIZE: 120,
} as const
