export const ANIMATION_CONFIG = {
  LOCK_ON_DELAY_MS: 195,
  INTER_MISSILE_PAUSE_MS: 130,
  MISSILE_FLIGHT_MS: 806,
  POST_COMBAT_SETTLE_MS: 494,
  BADGE_DRIFT_DELAY_S: 0.78,
  BADGE_DRIFT_DURATION_S: 0.65,
  TRAIL_LEN: 22,
  SYMBOL_DESIGN_SIZE: 120,
} as const
