import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { config } from '../packages/games/x7-club/src/constants'

const path = new URL('../apps/x7-server/config_generated.go', import.meta.url)
const expected = `// Code generated by bun scripts/x7-config.ts. DO NOT EDIT.
package main

const baseCost int64 = ${config.baseCost}
const buyCost int64 = ${config.buyCost}
const maxWinX int64 = ${config.maxWinX}
`
if (process.argv.includes('--check')) {
  if ((await readFile(path, 'utf8')) !== expected)
    throw new Error('Go math constants are stale. Run bun run x7:config')
  const source = await readFile(
    new URL('../packages/games/x7-club/config/config.json', import.meta.url),
  )
  const audit = JSON.parse(
    await readFile(
      new URL('../packages/games/x7-club/config/math-audit.json', import.meta.url),
      'utf8',
    ),
  ) as { configurationSha256: string }
  if (audit.configurationSha256 !== createHash('sha256').update(source).digest('hex'))
    throw new Error('X7 math audit does not match the configuration. Run bun run x7:audit')
} else {
  await writeFile(path, expected)
}
